development:
  sessions:
    default:
      database: bank_train_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: bank_train_test
      hosts:
        - localhost:27017